### ISSUE TITLE
`connection_relay_send` fails non-deterministically

### ISSUE THREAD

**Issue by kantai** [blockstack/stacks-blockchain#1322]
`net::connection::test::connection_relay_send` appears non-deterministic.

Every few times I run `cargo test net::connection::test::connection_relay_send -- --test-threads 1`, the test will fail for some reason.

**Comment by jcnelson** [comment]
Interesting.  Can you send me a stack trace if you see it again?  I haven't been able to reproduce it.

**Comment by kantai** [comment]
Yeah -- the test will fail due to an assertion check:

Either this one:

```
running 2 tests
test net::connection::test::connection_relay_send ... FAILED
test net::connection::test::connection_relay_send_recv ... ok

failures:

---- net::connection::test::connection_relay_send stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', src/net/connection.rs:1614:9
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:1412
   3: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
   4: std::panicking::default_hook::{{closure}}
   5: std::panicking::default_hook
   6: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   7: std::panicking::continue_panic_fmt
   8: std::thread::local::fast::Key<T>::try_initialize
   9: blockstack_lib::net::connection::test::connection_relay_send
             at src/net/connection.rs:1614
  10: blockstack_lib::net::connection::test::connection_relay_send::{{closure}}
             at src/net/connection.rs:1484
  11: core::ops::function::FnOnce::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  13: panic_unwind::dwarf::eh::read_encoded_pointer
  14: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  15: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  16: test::run_test_in_process
             at src/libtest/lib.rs:570
  17: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:473
  18: test::run_test::run_test_inner
             at src/libtest/lib.rs:494
  19: test::run_test
             at src/libtest/lib.rs:530
  20: test::run_tests
             at src/libtest/lib.rs:299
  21: test::console::run_tests_console
             at src/libtest/console.rs:295
  22: test::test_main
             at src/libtest/lib.rs:120
  23: test::test_main_static
             at src/libtest/lib.rs:139
  24: blockstack_lib::main
  25: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  26: std::panicking::try::do_call
  27: panic_unwind::dwarf::eh::read_encoded_pointer
  28: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
  29: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  30: blockstack_lib::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    net::connection::test::connection_relay_send

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 1015 filtered out

error: test failed, to rerun pass '--lib'
```

Or this one:

```
running 2 tests
test net::connection::test::connection_relay_send ... FAILED
test net::connection::test::connection_relay_send_recv ... ok

failures:

---- net::connection::test::connection_relay_send stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `5`,
 right: `4`', src/net/connection.rs:1551:9
stack backtrace:
   0: std::sys_common::at_exit_imp::push
   1: core::fmt::ArgumentV1::show_usize
   2: std::io::Write::write_fmt
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/io/mod.rs:1412
   3: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
   4: std::panicking::default_hook::{{closure}}
   5: std::panicking::default_hook
   6: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
   7: std::panicking::continue_panic_fmt
   8: std::thread::local::fast::Key<T>::try_initialize
   9: blockstack_lib::net::connection::test::connection_relay_send
             at src/net/connection.rs:1551
  10: blockstack_lib::net::connection::test::connection_relay_send::{{closure}}
             at src/net/connection.rs:1484
  11: core::ops::function::FnOnce::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/ops/function.rs:227
  12: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/liballoc/boxed.rs:942
  13: panic_unwind::dwarf::eh::read_encoded_pointer
  14: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  15: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  16: test::run_test_in_process
             at src/libtest/lib.rs:570
  17: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:473
  18: test::run_test::run_test_inner
             at src/libtest/lib.rs:494
  19: test::run_test
             at src/libtest/lib.rs:530
  20: test::run_tests
             at src/libtest/lib.rs:299
  21: test::console::run_tests_console
             at src/libtest/console.rs:295
  22: test::test_main
             at src/libtest/lib.rs:120
  23: test::test_main_static
             at src/libtest/lib.rs:139
  24: blockstack_lib::main
  25: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  26: std::panicking::try::do_call
  27: panic_unwind::dwarf::eh::read_encoded_pointer
  28: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
  29: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  30: blockstack_lib::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    net::connection::test::connection_relay_send

test result: FAILED. 1 passed; 1 failed; 0 ignored; 0 measured; 1015 filtered out

error: test failed, to rerun pass '--lib'
```

**Comment by kantai** [comment]
Relatedly -- `test_http_slow_client` also appears to fail occasionally (see the CircleCI failure on #1326)

```
DEBUG [1584125297.989] [src/chainstate/stacks/index/storage.rs:1356] Rename "/tmp/blockstack-test-peer-test_http_slow_client-51050/burn/marf/00/00/1900000000000000000000000000000000000000000000000000000000000000.tmp" to "/tmp/blockstack-test-peer-test_http_slow_client-51050/burn/marf/00/00/1900000000000000000000000000000000000000000000000000000000000000"
thread 'main' panicked at 'assertion failed: check_result(i, resp)', src/net/server.rs:558:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/io/mod.rs:1426
   6: std::io::impls::<impl std::io::Write for alloc::boxed::Box<W>>::write_fmt
             at src/libstd/io/impls.rs:156
   7: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   8: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   9: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
  10: std::panicking::default_hook
             at src/libstd/panicking.rs:221
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  12: std::panicking::begin_panic
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/panicking.rs:397
  13: blockstack_lib::net::server::test::test_http_server
             at src/net/server.rs:558
  14: blockstack_lib::net::server::test::test_http_slow_client
             at src/net/server.rs:718
  15: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/liballoc/boxed.rs:1017
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  17: std::panicking::try
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/panicking.rs:281
  18: std::panic::catch_unwind
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/panic.rs:394
  19: test::run_test_in_process
             at src/libtest/lib.rs:542
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:451
  21: test::run_test::run_test_inner
             at src/libtest/lib.rs:476
  22: test::run_test
             at src/libtest/lib.rs:506
  23: test::run_tests
             at src/libtest/lib.rs:285
  24: test::console::run_tests_console
             at src/libtest/console.rs:280
  25: test::test_main
             at src/libtest/lib.rs:121
  26: test::test_main_static
             at src/libtest/lib.rs:140
  27: std::rt::lang_start::{{closure}}
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/rt.rs:67
  28: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  29: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  30: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  31: std::panicking::try
             at src/libstd/panicking.rs:281
  32: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  33: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  34: std::rt::lang_start
             at /rustc/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/libstd/rt.rs:67
  35: __libc_start_main
  36: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    net::server::test::test_http_slow_client
```

**Comment by njordhov** [comment]
Same issue for #1320 where CircleCI fails with `net::server::test::test_http_slow_client`.

**Comment by kantai** [comment]
I don't think this is resolved, actually -- net::server::test::test_http_slow_client is still failing non-deterministically. See the CircleCI logs for a few different PRs, e.g.:

https://circleci.com/gh/blockstack/stacks-blockchain/5216
