### ISSUE TITLE
cargo build on Windows fails - thread 'main' panicked

### ISSUE THREAD

**Issue by fluidvoice** [blockstack/stacks-blockchain#1349]
some screenshots of install config below: 
ENV and full build output here: https://pastebin.com/8aJJ5r5H

> C:\Users\brad\Downloads\blockstack\stacks-blockchain>cargo build
>    Compiling sha2-asm v0.5.3
>    Compiling bitflags v1.2.1
>    Compiling log v0.4.8
>    Compiling quote v1.0.3
>    Compiling generic-array v0.12.3
> error: failed to run custom build command for `sha2-asm v0.5.3`
> 
> Caused by:
>   process didn't exit successfully: `C:\Users\brad\Downloads\blockstack\stacks-blockchain\target\debug\build\sha2-asm-9daad85244c117f3\build-script-build` (exit code: 101)
> --- stdout
> TARGET = Some("i686-pc-windows-msvc")
> OPT_LEVEL = Some("0")
> HOST = Some("i686-pc-windows-msvc")
> CC_i686-pc-windows-msvc = None
> CC_i686_pc_windows_msvc = None
> HOST_CC = None
> CC = None
> CFLAGS_i686-pc-windows-msvc = None
> CFLAGS_i686_pc_windows_msvc = None
> HOST_CFLAGS = None
> CFLAGS = None
> DEBUG = Some("true")
> running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\cl.exe" "/nologo" "/MD" "/Z7" "/W4" "-c" "/FoC:\\Users\\brad\\Downloads\\blockstack\\stacks-blockchain\\target\\debug\\build\\sha2-asm-fa9ffe49738fb710\\out\\src/sha512_x86.o" "/c" "src/sha512_x86.S"
> cargo:warning=cl : Command line warning D9024 : unrecognized source file type 'src/sha512_x86.S', object file assumed
> cargo:warning=cl : Command line warning D9027 : source file 'src/sha512_x86.S' ignored
> cl : Command line warning D9021 : no action performed
> exit code: 0
> running: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\lib.exe" "/OUT:C:\\Users\\brad\\Downloads\\blockstack\\stacks-blockchain\\target\\debug\\build\\sha2-asm-fa9ffe49738fb710\\out\\libsha512.a" "/nologo" "C:\\Users\\brad\\Downloads\\blockstack\\stacks-blockchain\\target\\debug\\build\\sha2-asm-fa9ffe49738fb710\\out\\src/sha512_x86.o"
> LINK : fatal error LNK1181: cannot open input file 'C:\Users\brad\Downloads\blockstack\stacks-blockchain\target\debug\build\sha2-asm-fa9ffe49738fb710\out\src\sha512_x86.o'
> exit code: 1181
> 
> --- stderr
> thread 'main' panicked at '
> 
> Internal error occurred: Command "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.25.28610\\bin\\HostX86\\x86\\lib.exe" "/OUT:C:\\Users\\brad\\Downloads\\blockstack\\stacks-blockchain\\target\\debug\\build\\sha2-asm-fa9ffe49738fb710\\out\\libsha512.a" "/nologo" "C:\\Users\\brad\\Downloads\\blockstack\\stacks-blockchain\\target\\debug\\build\\sha2-asm-fa9ffe49738fb710\\out\\src/sha512_x86.o" with args "lib.exe" did not execute successfully (status code exit code: 1181).
> 
> ', C:\Users\brad\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.26\src\lib.rs:2295:5
> stack backtrace:
>    0:   0xf428ed - core::fmt::write
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libcore\fmt\mod.rs:1052
>    1:   0xf29d21 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\io\mod.rs:1426
>    2:   0xf30eca - std::sys_common::backtrace::_print
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:62
>    3:   0xf30eca - std::sys_common::backtrace::print
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\sys_common\backtrace.rs:49
>    4:   0xf30eca - std::panicking::default_hook::{{closure}}
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:204
>    5:   0xf30ae5 - std::panicking::default_hook
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:224
>    6:   0xf3150a - std::panicking::rust_panic_with_hook
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:472
>    7:   0xf31128 - std::panicking::begin_panic_handler
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:380
>    8:   0xf31083 - std::panicking::begin_panic_fmt
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:334
>    9:   0xeaa00b - cc::fail
>                        at C:\Users\brad\.cargo\registry\src\github.com-1ecc6299db9ec823\cc-1.0.26\src\lib.rs:2295
>   10:   0xe91203 - build_script_build::main
>                        at C:\Users\brad\.cargo\registry\src\github.com-1ecc6299db9ec823\sha2-asm-0.5.3\build.rs:16
>   11:   0xe91203 - build_script_build::main
>                        at C:\Users\brad\.cargo\registry\src\github.com-1ecc6299db9ec823\sha2-asm-0.5.3\build.rs:16
>   12:   0xe91071 - std::rt::lang_start::{{closure}}<()>
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
>   13:   0xf2ef74 - std::rt::lang_start_internal::{{closure}}::{{closure}}
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
>   14:   0xf2ef74 - std::sys_common::backtrace::__rust_begin_short_backtrace<closure-0,i32>
>   15:   0xf31011 - std::rt::lang_start_internal::{{closure}}
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:52
>   16:   0xf31011 - std::panicking::try::do_call<closure-0,i32>
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:305
>   17:   0xf3992c - panic_unwind::__rust_maybe_catch_panic
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libpanic_unwind\lib.rs:86
>   18:   0xf3171f - std::panicking::try
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panicking.rs:281
>   19:   0xf3171f - std::panic::catch_unwind
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\panic.rs:394
>   20:   0xf3171f - std::rt::lang_start_internal
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\/src\libstd\rt.rs:51
>   21:   0xe9104d - std::rt::lang_start<()>
>                        at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\rt.rs:67
>   22:   0xe91321 - main
>   23: 0x76e66359 - BaseThreadInitThunk
>   24: 0x77ab7b74 - RtlGetAppContainerNamedObjectPath
>   25: 0x77ab7b44 - RtlGetAppContainerNamedObjectPath
> 
> warning: build failed, waiting for other jobs to finish...
> error: build failed

**Comment by fluidvoice** [comment]
![MS-VS-build-tools](https://user-images.githubusercontent.com/373038/77486753-50f4b280-6e0f-11ea-9d49-f0458aa6aaa0.PNG)
![advapi32 fix1](https://user-images.githubusercontent.com/373038/77486770-5c47de00-6e0f-11ea-8e49-7f32adb3465f.PNG)
![advapi32 fix2](https://user-images.githubusercontent.com/373038/77486777-5fdb6500-6e0f-11ea-9f16-d440a458890f.PNG)
