### ISSUE TITLE
Testnet panics on `NoSuchContract ` contract-call tx

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1384]
The node crashes when rerforming a contract-call tx that results in a `NoSuchContract` error:

```
WARN [1585816220.752] [src/chainstate/stacks/db/transactions.rs:422] Invalid contract-call transaction c8bfb71c4cf85f02a5b9911d8dd5a5d584b1c6950a18a5cff8fac35e6fb11d00: Interpreter(Unchecked(NoSuchContract("ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH.hello-world-contract")))
ERROR [1585816220.752] [src/testnet/helium/tenure.rs:66] Failed mining transaction - Unchecked(NoSuchContract("ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH.hello-world-contract"))
Burnchain block #9 (4e6e6acef5953a6a2087d8dd7d38a49b3ca0627d8ab339872ce56c5bd3b5a112) was produced with sortition #cccd23d27fcc9e8f38a1112eee12a1bd9146d1c23bcff5d0a1030abc1bb3ec5a
WARN [1585816220.834] [src/chainstate/stacks/db/blocks.rs:2481] Block 9103b7e1006e7a098064ba2ad811a13914beec8c239d93bb8db0c5ce277c010a state root mismatch: expected 28749d94aecd10a84df18a458c0b1a11ed8e4d5a33633087da409a35f253fc2e, got 6f0c51dc943b82f642ab5ae49c1c41dec1bcb204d0a142cafc1bf8a4cbdbe37f
thread 'main' panicked at 'Error while processing block - InvalidStacksBlock("Block 9103b7e1006e7a098064ba2ad811a13914beec8c239d93bb8db0c5ce277c010a state root mismatch: expected 28749d94aecd10a84df18a458c0b1a11ed8e4d5a33633087da409a35f253fc2e, got 6f0c51dc943b82f642ab5ae49c1c41dec1bcb204d0a142cafc1bf8a4cbdbe37f")', src/testnet/helium/node.rs:333:27
```

**Comment by jcnelson** [comment]
Hey @zone117x, can you try PR #1379?  I think it fixes this.

**Comment by zone117x** [comment]
Still running into the problem after a failed deploy-contract tx:

```
Node starting new tenure with VRF 05fe5b2b30267ecdf00ea3f273ed29f8fa070b393e093a35a2bf05a800b51afe
0x4576656e74212048656c6c6f20776f726c64
INFO [1585912586.279] [src/chainstate/stacks/db/transactions.rs:312] Post-condition check failure: No checks for fungible token type AssetIdentifier { contract_identifier: QualifiedContractIdentifier { issuer: StandardPrincipalData(26, [191, 142, 130, 98, 60, 56, 12, 216, 112, 147, 29, 72, 181, 37, 213, 225, 42, 77, 103, 130]), name: ContractName("kv-store") }, asset_name: ClarityName("novel-token-19") } moved by Standard(StandardPrincipalData(31, [164, 111, 248, 136, 134, 194, 239, 151, 98, 217, 112, 180, 210, 198, 54, 120, 131, 91, 211, 157]))
Burnchain block #12 (dcb20558bd220be59a3d7f0091a128adb350093364276bcc7efd1ffebe16111e) was produced with sortition #6acd8c283c7c343669624d312509ed9f0f084eb041da90e0145c0b5a3b5096f1
0x4576656e74212048656c6c6f20776f726c64
INFO [1585912586.663] [src/chainstate/stacks/db/transactions.rs:299] Post-condition check failure: No checks for any non-fungible assets, but moved AssetIdentifier { contract_identifier: QualifiedContractIdentifier { issuer: StandardPrincipalData(26, [191, 142, 130, 98, 60, 56, 12, 216, 112, 147, 29, 72, 181, 37, 213, 225, 42, 77, 103, 130]), name: ContractName("kv-store") }, asset_name: ClarityName("hello-nft") } by Standard(StandardPrincipalData(31, [164, 111, 248, 136, 134, 194, 239, 151, 98, 217, 112, 180, 210, 198, 54, 120, 131, 91, 211, 157]))
Stacks block #11 (3024fbd3f3f06346bf445de6458259bd3e91e3621f14d04dd152d4d88a74716c) successfully produced, including 2 transactions
-> Tx issued by bf1adf459044dfae99f5502ea2ae38fbd9654df8 (fee: 0, nonce: 10)
   Coinbase
-> Tx issued by bf8e82623c380cd870931d48b525d5e12a4d6782 (fee: 9, nonce: 0)
   Publish smart contract
**************************
(define-constant sender 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR)
    (define-constant recipient 'SM2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQVX8X0G)
    
    (define-fungible-token novel-token-19)
    (begin (ft-mint? novel-token-19 u12 sender))
    (begin (ft-transfer? novel-token-19 u2 sender recipient))
    
    (define-non-fungible-token hello-nft uint)
    (begin (nft-mint? hello-nft u1 sender))
    (begin (nft-mint? hello-nft u2 sender))
    (begin (nft-transfer? hello-nft u1 sender recipient))
    
    (define-public (test-emit-event)
        (begin
            (print "Event! Hello world")
            (ok u1)))
    (begin (test-emit-event))
    
    (define-public (test-event-types)
        (begin
            (unwrap-panic (ft-mint? novel-token-19 u3 recipient))
            (unwrap-panic (nft-mint? hello-nft u2 recipient))
            (unwrap-panic (stx-transfer? u60 tx-sender 'SZ2J6ZY48GV1EZ5V2V5RB9MP66SW86PYKKQ9H6DPR))
            (unwrap-panic (stx-burn? u20 tx-sender))
            (ok 'true)))
    
    (define-map store ((key (buff 32))) ((value (buff 32))))
    (define-public (get-value (key (buff 32)))
        (begin
            (match (map-get? store ((key key)))
                entry (ok (get value entry))
                (err 0))))
    (define-public (set-value (key (buff 32)) (value (buff 32)))
        (begin
            (map-set store ((key key)) ((value value)))
            (ok 'true)))
**************************
Node starting new tenure with VRF 272bf2261ca435e3b9cf752971e84cfcf2944c82d335ba396ff4fb183872097c
Burnchain block #13 (986044cccd0d6429072e2329bbf203700420754cb6e1ba4a946a8bd640974fa6) was produced with sortition #716bfed42e43c9ecad829034d5ede351a596a43583c5b2bf43b1a7bf262c301f
Stacks block #12 (22cd93c763643ffe1c97493453ef4d91333bd06c41d21962f18672d77c74beb4) successfully produced, including 1 transactions
-> Tx issued by bf1adf459044dfae99f5502ea2ae38fbd9654df8 (fee: 0, nonce: 11)
   Coinbase

[....]

Node starting new tenure with VRF 922d732682f21b9a5aba0cd362453ddd572384352db0c758fc95cf6867df5ad0
Burnchain block #20 (98211882bd13089b6ccf1fca81f7f0e4abf6352a0c39c9b11f142cac233f1280) was produced with sortition #5960a85a783bd26db899ed3dacdb19836e32971d722f85ee8973b918f61846c7
Stacks block #19 (62f5b8fdf3ea8646456cf4a76faea705e776a0dedffe1686718ab5e434358f9e) successfully produced, including 1 transactions
-> Tx issued by bf1adf459044dfae99f5502ea2ae38fbd9654df8 (fee: 0, nonce: 18)
   Coinbase
Node starting new tenure with VRF 87c56b0406974371d2a2bb1c0498b5abe80ae8a801de9af15301025094b776fb
WARN [1585912633.469] [src/chainstate/stacks/db/transactions.rs:422] Invalid contract-call transaction 7672ca7a8cb98f51f4f3281a76f54cafc7642ca0ab3bb4b2bb042da5112832e7: Interpreter(Unchecked(NoSuchContract("ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH.kv-store")))
ERROR [1585912633.470] [src/testnet/helium/tenure.rs:66] Failed mining transaction - Unchecked(NoSuchContract("ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH.kv-store"))
Burnchain block #21 (790b3a74cf894b432a2586a29937612952840cb1f21f391db99ad88ed8ca54bd) was produced with sortition #f9af27717de7af5cd597d2d870fa72fa9a8a97825d7367c510972f75bafcbcec
WARN [1585912633.563] [src/chainstate/stacks/db/blocks.rs:2522] Block 189ebd91e6ee5635c6b254696a7ba5754bfc3d73c0cf2e09d8841676abc3580c state root mismatch: expected 43363a440231075801fe0fc4643492b5ee386510e20804b9d57a6baaa3085390, got cdec7e73d2365a56b45087b299db062fc96eb60e70f645b1369c371b1310dc2f
WARN [1585912633.577] [src/chainstate/stacks/db/blocks.rs:2790] Encountered invalid block: Block 189ebd91e6ee5635c6b254696a7ba5754bfc3d73c0cf2e09d8841676abc3580c state root mismatch: expected 43363a440231075801fe0fc4643492b5ee386510e20804b9d57a6baaa3085390, got cdec7e73d2365a56b45087b299db062fc96eb60e70f645b1369c371b1310dc2f
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10
stack backtrace:
   0:        0x100e0b1c5 - backtrace::backtrace::libunwind::trace::h5c84db184dbe55ed
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:        0x100e0b1c5 - backtrace::backtrace::trace_unsynchronized::hfabf504f184a4062
                               at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:        0x100e0b1c5 - std::sys_common::backtrace::_print_fmt::hb18545a457444b58
                               at src/libstd/sys_common/backtrace.rs:77
   3:        0x100e0b1c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hff7732c2e44ef8b9
                               at src/libstd/sys_common/backtrace.rs:59
   4:        0x100e29ecd - core::fmt::write::hd42cb3dea57bae40
                               at src/libcore/fmt/mod.rs:1052
   5:        0x100e0771b - std::io::Write::write_fmt::ha39f6009af02b1d2
                               at src/libstd/io/mod.rs:1426
   6:        0x100e0d55a - std::sys_common::backtrace::_print::h5cfb8cdd320f1e64
                               at src/libstd/sys_common/backtrace.rs:62
   7:        0x100e0d55a - std::sys_common::backtrace::print::hef683e3bc77ce269
                               at src/libstd/sys_common/backtrace.rs:49
   8:        0x100e0d55a - std::panicking::default_hook::{{closure}}::h389f076017b5df43
                               at src/libstd/panicking.rs:204
   9:        0x100e0d25a - std::panicking::default_hook::h04b06ec20c41bf02
                               at src/libstd/panicking.rs:224
  10:        0x100e0dbad - std::panicking::rust_panic_with_hook::hccde7faed9a5c398
                               at src/libstd/panicking.rs:472
  11:        0x100e0d772 - rust_begin_unwind
                               at src/libstd/panicking.rs:380
  12:        0x100e3b71f - std::panicking::begin_panic::hc520a8a43176ea4c
  13:        0x100e3b6e9 - std::panicking::begin_panic::hc520a8a43176ea4c
  14:        0x1008ac0ef - <blockstack_lib::chainstate::burn::BlockSnapshot as core::clone::Clone>::clone::h1583de78cce1ce30
  15:        0x100933ba5 - <blockstack_lib::vm::costs::ExecutionCost as core::clone::Clone>::clone::h8761deb0a92c3773
  16:        0x1004d2beb - <alloc::vec::Vec<T> as core::ops::index::Index<I>>::index::hc0037634d8bbdf90
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/liballoc/vec.rs:1883
  17:        0x1002708c1 - blockstack_lib::testnet::helium::node::Node::process_tenure::h76ddc0a1bca6587e
                               at src/testnet/helium/node.rs:346
  18:        0x1002693cd - blockstack_lib::testnet::helium::run_loop::RunLoop::start::hf0112ef440c4c667
                               at src/testnet/helium/run_loop.rs:191
  19:        0x100070ad0 - blockstack_core::main::h226cbcce8140340a
                               at src/main.rs:205
  20:        0x1000717d2 - std::rt::lang_start::{{closure}}::h7d8710363651aec7
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  21:        0x100e0d678 - std::rt::lang_start_internal::{{closure}}::hd38dd0e12f275c20
                               at src/libstd/rt.rs:52
  22:        0x100e0d678 - std::panicking::try::do_call::hf2b35caddf59127c
                               at src/libstd/panicking.rs:305
  23:        0x100e113cb - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  24:        0x100e0df6e - std::panicking::try::hc278c045b5a17f13
                               at src/libstd/panicking.rs:281
  25:        0x100e0df6e - std::panic::catch_unwind::h21f9aef85494420b
                               at src/libstd/panic.rs:394
  26:        0x100e0df6e - std::rt::lang_start_internal::h8e563903bf99e7c1
                               at src/libstd/rt.rs:51
  27:        0x1000717b2 - std::rt::lang_start::hfe6f2c850b83a5b4
                               at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  28:        0x100071762 - blockstack_core::main::h226cbcce8140340a

```

**Comment by jcnelson** [comment]
Looks like it's happening in the Helium testnet node (cc @lgalabru)

**Comment by lgalabru** [comment]
Yes, these are the required changes I mentioned yesterday here https://github.com/blockstack/stacks-blockchain/pull/1379#pullrequestreview-386564469. Up until now, the testnet was expecting a block, witch is not anymore a guarantee with the last changes. Will open a separate PR instead of adding more changes to #1319.

**Comment by diwakergupta** [comment]
Potential dup of #1374, might merge.

**Comment by lgalabru** [comment]
@zone117x are you able to reproduce this crash with latest master?

**Comment by zone117x** [comment]
This is fixed on latest master, thanks!
