### ISSUE TITLE
Testnet panic at 'Clarity VM attempted to initialize existing token'

### ISSUE THREAD

**Issue by zone117x** [blockstack/stacks-blockchain#1429]
Reproduce by deploying the same smart contract source (with assets) from the same account but with different contract names.

```
stacks-blockchain_1  | thread 'main' panicked at 'Clarity VM attempted to initialize existing token', /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/vm/database/clarity_db.rs:509:9
stacks-blockchain_1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
stacks-blockchain_1  | thread 'main' panicked at 'BUG: Transaction connection lost cost_tracker handle.', /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/vm/clarity.rs:401:9
stacks-blockchain_1  | stack backtrace:
stacks-blockchain_1  |    0:     0x55834493d494 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
stacks-blockchain_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
stacks-blockchain_1  |    1:     0x55834493d494 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
stacks-blockchain_1  |                                at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
stacks-blockchain_1  |    2:     0x55834493d494 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
stacks-blockchain_1  |                                at src/libstd/sys_common/backtrace.rs:77
stacks-blockchain_1  |    3:     0x55834493d494 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
stacks-blockchain_1  |                                at src/libstd/sys_common/backtrace.rs:59
stacks-blockchain_1  |    4:     0x55834495e9ac - core::fmt::write::h4e6a29ee6319c9fd
stacks-blockchain_1  |                                at src/libcore/fmt/mod.rs:1052
stacks-blockchain_1  |    5:     0x558344936ee7 - std::io::Write::write_fmt::hf06b1c86d898d7d6
stacks-blockchain_1  |                                at src/libstd/io/mod.rs:1426
stacks-blockchain_1  |    6:     0x55834493fcc5 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
stacks-blockchain_1  |                                at src/libstd/sys_common/backtrace.rs:62
stacks-blockchain_1  |    7:     0x55834493fcc5 - std::sys_common::backtrace::print::hcc4377f1f882322e
stacks-blockchain_1  |                                at src/libstd/sys_common/backtrace.rs:49
stacks-blockchain_1  |    8:     0x55834493fcc5 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
stacks-blockchain_1  |                                at src/libstd/panicking.rs:204
stacks-blockchain_1  |    9:     0x55834493f9b1 - std::panicking::default_hook::h7a68887d113f8029
stacks-blockchain_1  |                                at src/libstd/panicking.rs:224
stacks-blockchain_1  |   10:     0x55834494032a - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
stacks-blockchain_1  |                                at src/libstd/panicking.rs:472
stacks-blockchain_1  |   11:     0x55834493ff10 - rust_begin_unwind
stacks-blockchain_1  |                                at src/libstd/panicking.rs:380
stacks-blockchain_1  |   12:     0x55834495d1f1 - core::panicking::panic_fmt::hb1f3e14b86a3520c
stacks-blockchain_1  |                                at src/libcore/panicking.rs:85
stacks-blockchain_1  |   13:     0x55834495cf83 - core::option::expect_failed::hec9609db448f63c6
stacks-blockchain_1  |                                at src/libcore/option.rs:1191
stacks-blockchain_1  |   14:     0x558344230165 - core::option::Option<T>::expect::hdef4e261b7956058
stacks-blockchain_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/option.rs:347
stacks-blockchain_1  |   15:     0x5583433db3f1 - <blockstack_lib::vm::clarity::ClarityTransactionConnection as core::ops::drop::Drop>::drop::hd919755b394477d1
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/vm/clarity.rs:401
stacks-blockchain_1  |   16:     0x558343bc3105 - core::ptr::drop_in_place::h56d2446f215da4a8
stacks-blockchain_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
stacks-blockchain_1  |   17:     0x55834416d848 - blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction::h34009a4f2269d98c
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/chainstate/stacks/db/transactions.rs:581
stacks-blockchain_1  |   18:     0x5583434b21b7 - blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::try_mine_tx::h7401d0ed363030fa
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/chainstate/stacks/miner.rs:122
stacks-blockchain_1  |   19:     0x558343cb3e81 - blockstack_lib::testnet::helium::tenure::LeaderTenure::handle_txs::h0ef62261beb2c937
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/testnet/helium/tenure.rs:64
stacks-blockchain_1  |   20:     0x558343cb42b1 - blockstack_lib::testnet::helium::tenure::LeaderTenure::run::h16a75a1534bfa9f2
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/testnet/helium/tenure.rs:86
stacks-blockchain_1  |   21:     0x558343a291df - blockstack_lib::testnet::helium::run_loop::RunLoop::start::h0b57bf8e21a5142b
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/testnet/helium/run_loop.rs:158
stacks-blockchain_1  |   22:     0x5583432d4f76 - blockstack_core::main::hc106f565f4935ad2
stacks-blockchain_1  |                                at /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/0c1cdd2/src/main.rs:204
stacks-blockchain_1  |   23:     0x5583432de2a0 - std::rt::lang_start::{{closure}}::h1177630b5073cb43
stacks-blockchain_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
stacks-blockchain_1  |   24:     0x55834493fdf3 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
stacks-blockchain_1  |                                at src/libstd/rt.rs:52
stacks-blockchain_1  |   25:     0x55834493fdf3 - std::panicking::try::do_call::he4701ab6e48d80c0
stacks-blockchain_1  |                                at src/libstd/panicking.rs:305
stacks-blockchain_1  |   26:     0x558344944e57 - __rust_maybe_catch_panic
stacks-blockchain_1  |                                at src/libpanic_unwind/lib.rs:86
stacks-blockchain_1  |   27:     0x5583449407d0 - std::panicking::try::hd3de25f3cb7024b8
stacks-blockchain_1  |                                at src/libstd/panicking.rs:281
stacks-blockchain_1  |   28:     0x5583449407d0 - std::panic::catch_unwind::h86c02743a24e3d92
stacks-blockchain_1  |                                at src/libstd/panic.rs:394
stacks-blockchain_1  |   29:     0x5583449407d0 - std::rt::lang_start_internal::h9cf8802361ad86c2
stacks-blockchain_1  |                                at src/libstd/rt.rs:51
stacks-blockchain_1  |   30:     0x5583432de279 - std::rt::lang_start::he90d80b8bb92c8fb
stacks-blockchain_1  |                                at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
stacks-blockchain_1  |   31:     0x5583432d660a - main
stacks-blockchain_1  |   32:     0x7f9cb4bd52e1 - __libc_start_main
stacks-blockchain_1  |   33:     0x558343234bea - _start
stacks-blockchain_1  |   34:                0x0 - <unknown>
stacks-blockchain_1  | thread panicked while panicking. aborting.
```

**Comment by kantai** [comment]
Yep -- this appears to be a bug in the FT/NFT initialization code -- FT and NFT initialization should _only_ impact metadata, but it appears to also be initializing data as well (looks like somebody, i.e., me, left a few lines in when implementing the metadata/data separation).
