### ISSUE TITLE
blockstack-cli: Error: Cannot find module '../lib/index'

### ISSUE THREAD

**Issue by kevinghim** [blockstack/stacks-blockchain#1514]
**Describe the bug**
blockstack-cli is throwing an error when trying to create a wallet. I'm following the instructions on https://docs.blockstack.org/core/smart/cli-wallet-quickstart.html

**Steps To Reproduce**
After using `npm install -g https://github.com/blockstack/cli-blockstack#feature/stacks-2.0-tx` to install blockstack-cli, I'm getting the following error when trying to create a wallet:

```
internal/modules/cjs/loader.js:983
  throw err;
  ^

Error: Cannot find module '../lib/index'
Require stack:
- /usr/local/lib/node_modules/blockstack-cli/cmd/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockstack-cli/cmd/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/blockstack-cli/cmd/index.js' ]
}

```

**Environment (please complete the following information):**
 - OS: Raspberry Pi 4, ARMv7, Raspbian GNU/Linux 10
 - Rust version: 6.14.4
 - Version of the appropriate binary / software package: stacks 2.0

**Comment by jcnelson** [comment]
Wrong repository.  Please file against https://github.com/blockstack/cli-blockstack.
