### ISSUE TITLE
Follower panicked at 'attempt to add with overflow'

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/stacks-blockchain#1543]
**Describe the bug**
Follower crashed with following stack trace:

```
thread '<unnamed>' panicked at 'attempt to add with overflow', src/util/db.rs:443:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.r
s:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: blockstack_lib::util::db::tx_busy_handler
             at src/util/db.rs:443
  16: rusqlite::busy::<impl rusqlite::Connection>::busy_handler::busy_handler_callback::{{closure}}
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/busy.rs:52
  17: std::panicking::try::do_call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  19: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  20: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  21: rusqlite::busy::<impl rusqlite::Connection>::busy_handler::busy_handler_callback
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/busy.rs:52
  22: sqlite3InvokeBusyHandler
             at sqlite3/sqlite3.c:154308
  23: btreeInvokeBusyHandler
             at sqlite3/sqlite3.c:65175
  24: sqlite3BtreeBeginTrans
             at sqlite3/sqlite3.c:66334
  25: sqlite3VdbeExec
             at sqlite3/sqlite3.c:86227
  26: sqlite3Step
             at sqlite3/sqlite3.c:81338
  27: sqlite3_step
             at sqlite3/sqlite3.c:81401
  28: sqlite3_exec
             at sqlite3/sqlite3.c:117981
  29: rusqlite::InnerConnection::execute_batch
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/lib.rs:930
  30: rusqlite::Connection::execute_batch
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/lib.rs:309
  31: rusqlite::transaction::Transaction::new
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/transaction.rs:101
  32: blockstack_lib::util::db::tx_begin_immediate
             at src/util/db.rs:458
  33: blockstack_lib::chainstate::burn::db::burndb::BurnDB::tx_begin
             at src/chainstate/burn/db/burndb.rs:1172
  34: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block
             at src/burnchains/burnchain.rs:749
  35: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::sync_with_indexer::{{closure}
}
             at src/burnchains/burnchain.rs:902
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
WARN [1588808783.267] [src/burnchains/burnchain.rs:936] Failed to join burnchain download thread: DBError(SqliteError(Sq
liteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))))
ERROR [1588808783.267] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:143] Unable to sync with burnch
ain: Try synchronizing again
```

**Steps To Reproduce**

Using this config (note I'm using the `working_dir`):
```toml
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@neon.blockstack.org:20444"
working_dir = "/Users/diwaker/Desktop/stacks-testnet-neon"

[burnchain]
chain = "bitcoin"
mode = "neon"
peer_host = "neon.blockstack.org"
rpc_port = 18443
peer_port = 18444

#mstx stanzas omitted
```

**Environment (please complete the following information):**
 - OS: OS X
 - git-rev dd6778e4d6c587d90fba9df692bb4a40b0c55ef3

**Additional context**
Also saw a lot of these in the logs:

```
WARN [1588808621.447] [testnet/stacks-node/src/neon_node.rs:239] Relayer buffer is full, dropping NetworkHandle
```

**Comment by jcnelson** [comment]
Already seen and fixed locally.  Making a PR after testing.
