### ISSUE TITLE
Errors with received headers with bad target or difficult when running the mining program

### ISSUE THREAD

**Issue by paradigma-cl** [blockstack/stacks-blockchain#1579]
**Describe the bug**
Receives headers with bad target difficult

**Steps To Reproduce**
Running the stacks-node with mining configuration

**Expected behavior**
It was working before

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Rust version
 - Version of the appropriate binary / software package

**Additional context**
DEBUG [1589399414.566] [src/burnchains/bitcoin/network.rs:368] Send GetHeaders 264e0f84c3ac6c1c22418bd039cc8c26b1528bce06fb41571358990c3edd20cd for 2000 headers to 35.245.47.179:18444
DEBUG [1589399415.056] [src/burnchains/bitcoin/spv.rs:308] Insert 2 headers to /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2005
DEBUG [1589399415.057] [src/burnchains/bitcoin/spv.rs:277] Write 2 headers at /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2005
DEBUG [1589399415.058] [src/burnchains/bitcoin/spv.rs:262] Handled 2 Headers: 3399a0121db2c5a7981400a2aa6e18bf662eb5549f120826f252080d4839967e-59187891c71ac49b79f1c603b36ce336fcfbf82e3af010c1099970f2eda90dc4
DEBUG [1589399415.059] [src/burnchains/bitcoin/spv.rs:453] Request headers for blocks 2007 - 4007 in range 0 - 3515
DEBUG [1589399415.060] [src/burnchains/bitcoin/network.rs:368] Send GetHeaders 59187891c71ac49b79f1c603b36ce336fcfbf82e3af010c1099970f2eda90dc4 for 2000 headers to 35.245.47.179:18444
DEBUG [1589399415.548] [src/burnchains/bitcoin/spv.rs:308] Insert 2 headers to /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2007
DEBUG [1589399415.549] [src/burnchains/bitcoin/spv.rs:277] Write 2 headers at /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2007
DEBUG [1589399415.559] [src/burnchains/bitcoin/spv.rs:262] Handled 2 Headers: 5219522b1f7f01b79f5e4e85b840b98a4ecd975a5caf80b3ed1dc597e2b05996-343c15b80eb779fad9c5e07924d8b469c0fe8434bde9ec1702f7043c4cb01f95
DEBUG [1589399415.559] [src/burnchains/bitcoin/spv.rs:453] Request headers for blocks 2009 - 4009 in range 0 - 3515
DEBUG [1589399415.559] [src/burnchains/bitcoin/network.rs:368] Send GetHeaders 343c15b80eb779fad9c5e07924d8b469c0fe8434bde9ec1702f7043c4cb01f95 for 2000 headers to 35.245.47.179:18444
DEBUG [1589399416.043] [src/burnchains/bitcoin/spv.rs:308] Insert 2 headers to /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2009
DEBUG [1589399416.044] [src/burnchains/bitcoin/spv.rs:277] Write 2 headers at /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2009
DEBUG [1589399416.045] [src/burnchains/bitcoin/spv.rs:262] Handled 2 Headers: 6cfd9bfa53c76f27b1c6cb24d297dbacc89408ed4c721cafc7c1cf60c4d28343-0f5d70d8a5156b3e753653777b061b29738badbea9efde71011cd13b1f3b6f23
DEBUG [1589399416.046] [src/burnchains/bitcoin/spv.rs:453] Request headers for blocks 2011 - 4011 in range 0 - 3515
DEBUG [1589399416.047] [src/burnchains/bitcoin/network.rs:368] Send GetHeaders 0f5d70d8a5156b3e753653777b061b29738badbea9efde71011cd13b1f3b6f23 for 2000 headers to 35.245.47.179:18444
DEBUG [1589399416.543] [src/burnchains/bitcoin/spv.rs:308] Insert 2 headers to /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2011
DEBUG [1589399416.543] [src/burnchains/bitcoin/spv.rs:277] Write 2 headers at /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2011
DEBUG [1589399416.544] [src/burnchains/bitcoin/spv.rs:262] Handled 2 Headers: 254df177d0657cdf8f25ef67e4b093a8ee75e1412482e76bfd074f14470da05c-4ce6f73b1fa05529da12d3ff208f834bf10794aec563730c8078bbe0bc24dd46
DEBUG [1589399416.545] [src/burnchains/bitcoin/spv.rs:453] Request headers for blocks 2013 - 4013 in range 0 - 3515
DEBUG [1589399416.545] [src/burnchains/bitcoin/network.rs:368] Send GetHeaders 4ce6f73b1fa05529da12d3ff208f834bf10794aec563730c8078bbe0bc24dd46 for 2000 headers to 35.245.47.179:18444
DEBUG [1589399417.006] [src/burnchains/bitcoin/spv.rs:308] Insert 2 headers to /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2013
DEBUG [1589399417.007] [src/burnchains/bitcoin/spv.rs:277] Write 2 headers at /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2013
DEBUG [1589399417.007] [src/burnchains/bitcoin/spv.rs:262] Handled 2 Headers: 206dcafa14a8623f64757af72e1d7549461b1064a524c63699cdf7b62807389c-148a196a372416f7c40dccd7dcdd16400704861d8349d6c4396d4e5f03fb9410
DEBUG [1589399417.008] [src/burnchains/bitcoin/spv.rs:453] Request headers for blocks 2015 - 4015 in range 0 - 3515
DEBUG [1589399417.009] [src/burnchains/bitcoin/network.rs:368] Send GetHeaders 148a196a372416f7c40dccd7dcdd16400704861d8349d6c4396d4e5f03fb9410 for 2000 headers to 35.245.47.179:18444
DEBUG [1589399417.478] [src/burnchains/bitcoin/spv.rs:308] Insert 2 headers to /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2015
DEBUG [1589399417.480] [src/burnchains/bitcoin/spv.rs:277] Write 2 headers at /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg at 2015
ERROR [1589399417.482] [src/burnchains/bitcoin/spv.rs:152] bits mismatch at block 2016 of /tmp/stacks-testnet-89fa967147ac015a/burnchain/spv-headers.dat.reorg (offset 0 interval 1 of 1-2): 545259519 != 486604799
ERROR [1589399417.483] [src/burnchains/bitcoin/spv.rs:257] Received headers with bad target or difficulty
WARN [1589399417.483] [src/burnchains/bitcoin/indexer.rs:414] Unhandled error InvalidPoW
ERROR [1589399417.483] [src/burnchains/bitcoin/indexer.rs:508] Failed to fetch headers from 0 - 16
ERROR [1589399417.483] [src/burnchains/burnchain.rs:794] Failed to check for reorgs from 0
ERROR [1589399417.484] [testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid proof of work
thread 'main' panicked at 'explicit panic', testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
stack backtrace:
   0:     0x5589b5844994 - backtrace::backtrace::libunwind::trace::h90669f559fb267f0
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1:     0x5589b5844994 - backtrace::backtrace::trace_unsynchronized::hffde4e353d8f2f9a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2:     0x5589b5844994 - std::sys_common::backtrace::_print_fmt::heaf44068b7eaaa6a
                               at src/libstd/sys_common/backtrace.rs:77
   3:     0x5589b5844994 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h88671019cf081de2
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x5589b58654dc - core::fmt::write::h4e6a29ee6319c9fd
                               at src/libcore/fmt/mod.rs:1052
   5:     0x5589b583e017 - std::io::Write::write_fmt::hf06b1c86d898d7d6
                               at src/libstd/io/mod.rs:1426
   6:     0x5589b5846b95 - std::sys_common::backtrace::_print::h404ff5f2b50cae09
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x5589b5846b95 - std::sys_common::backtrace::print::hcc4377f1f882322e
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x5589b5846b95 - std::panicking::default_hook::{{closure}}::hc172eff6f35b7f39
                               at src/libstd/panicking.rs:204
   9:     0x5589b5846881 - std::panicking::default_hook::h7a68887d113f8029
                               at src/libstd/panicking.rs:224
  10:     0x5589b58471fa - std::panicking::rust_panic_with_hook::hb7ad5693188bdb00
                               at src/libstd/panicking.rs:472
  11:     0x5589b4da9aae - std::panicking::begin_panic::h8eb3774ca6f2d47f
  12:     0x5589b4dc59ba - stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestController::receive_blocks::h9cdb383c7d1bba28
  13:     0x5589b4ddc6f0 - stacks_node::run_loop::neon::RunLoop::start::hf9bfdc08e2b528a0
  14:     0x5589b4ce39fb - stacks_node::main::h05b4b7e36e1a54b9
  15:     0x5589b4cd19b3 - std::rt::lang_start::{{closure}}::h5527f249c068a88e
  16:     0x5589b5846cc3 - std::rt::lang_start_internal::{{closure}}::hb26e39676675046f
                               at src/libstd/rt.rs:52
  17:     0x5589b5846cc3 - std::panicking::try::do_call::he4701ab6e48d80c0
                               at src/libstd/panicking.rs:305
  18:     0x5589b584b8f7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  19:     0x5589b5847760 - std::panicking::try::hd3de25f3cb7024b8
                               at src/libstd/panicking.rs:281
  20:     0x5589b5847760 - std::panic::catch_unwind::h86c02743a24e3d92
                               at src/libstd/panic.rs:394
  21:     0x5589b5847760 - std::rt::lang_start_internal::h9cf8802361ad86c2
                               at src/libstd/rt.rs:51
  22:     0x5589b4ce5902 - main
  23:     0x7f37a0588b97 - __libc_start_main
  24:     0x5589b4c9639a - _start
  25:                0x0 - <unknown>.

**Comment by paradigma-cl** [comment]
Now working
