### ISSUE TITLE
peer_host in config file should accept an IP or FQDN

### ISSUE THREAD

**Issue by CharlieC3** [blockstack/stacks-blockchain#1611]
**Describe the bug**
The `peer_host` property under the `[burnchain]` section currently only accepts an IP address as a valid value. Using an FQDN for the value causes an error in the log output.

**Steps To Reproduce**
Run the stacks-blockchain docker container, passing in the following args:
`start --config <PATH TO CONFIG FILE INSIDE DOCKER CONTAINER>`
using a config file with the `peer_host` property under the `[burnchain]` section set to an FQDN.

**Expected behavior**
stacks-blockchain should accept an IP address _or_ FQDN as a valid value for the `peer_host` property under the `[burnchain]` section in its config file.

**Additional context**
```
==> /src/stacks-blockchain/god-node-conf.toml
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "failed to lookup address information: Name does not resolve" }', testnet/stacks-node/src/config.rs:241:50
stack backtrace:
   0:          0x10287a4 - backtrace::backtrace::libunwind::trace::h054f55e3dc06bc5e
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:          0x10287a4 - backtrace::backtrace::trace_unsynchronized::h1186ac2475a6fb30
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:          0x10287a4 - std::sys_common::backtrace::_print_fmt::h461344b5d95acdca
                               at src/libstd/sys_common/backtrace.rs:78
   3:          0x10287a4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6282cf42b714e880
                               at src/libstd/sys_common/backtrace.rs:59
   4:          0x1069c3c - core::fmt::write::hc2a3a9db73907d34
                               at src/libcore/fmt/mod.rs:1063
   5:          0x1020fe3 - std::io::Write::write_fmt::h99f78802c17ed488
                               at src/libstd/io/mod.rs:1426
   6:          0x102afe5 - std::sys_common::backtrace::_print::h81d44cbe95d725dc
                               at src/libstd/sys_common/backtrace.rs:62
   7:          0x102afe5 - std::sys_common::backtrace::print::h0fc8ade31453f483
                               at src/libstd/sys_common/backtrace.rs:49
   8:          0x102afe5 - std::panicking::default_hook::{{closure}}::hbd2f47050b7511e4
                               at src/libstd/panicking.rs:204
   9:          0x102ad32 - std::panicking::default_hook::hc7cc8bcc86ad3d5f
                               at src/libstd/panicking.rs:224
  10:          0x102b642 - std::panicking::rust_panic_with_hook::hc3b9a5b3f9266bae
                               at src/libstd/panicking.rs:470
  11:          0x102b22b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:          0x1068351 - core::panicking::panic_fmt::h9eaff8afd9ffd7d8
                               at src/libcore/panicking.rs:85
  13:          0x1068173 - core::option::expect_none_failed::hcbd323a6f68cb13c
                               at src/libcore/option.rs:1211
  14:           0x526d33 - stacks_node::config::Config::from_config_file::h011edad3eca9bca6
  15:           0x442091 - stacks_node::main::hd4ecff8c76b0a8cf
  16:           0x48d6c3 - std::rt::lang_start::{{closure}}::h7c30fab6934069e9
  17:          0x102b103 - std::rt::lang_start_internal::{{closure}}::heb26da7d989b514e
                               at src/libstd/rt.rs:52
  18:          0x102b103 - std::panicking::try::do_call::h9d237957d01cdc63
                               at src/libstd/panicking.rs:303
  19:          0x102f2d7 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:          0x102bb03 - std::panicking::try::h1df9f1b1bbe4e51f
                               at src/libstd/panicking.rs:281
  21:          0x102bb03 - std::panic::catch_unwind::h18bbd8c959d3ef0c
                               at src/libstd/panic.rs:394
  22:          0x102bb03 - std::rt::lang_start_internal::h38d5526f55e52600
                               at src/libstd/rt.rs:51
  23:           0x442722 - main
```

**Comment by CharlieC3** [comment]
I believe this logic will need to be updated to close the issue:
https://github.com/blockstack/stacks-blockchain/blob/master/testnet/stacks-node/src/config.rs#L241-L243

**Comment by jcnelson** [comment]
Hi @CharlieC3, what was the FQDN you used?

**Comment by CharlieC3** [comment]
@jcnelson I was using the FQDN `neon.staging-core.service.cluster.local`, to be used in our K8s staging cluster.

**Comment by jcnelson** [comment]
Okay, so, the code you highlighted just uses the local DNS resolver.  If that name doesn't resolve in the first place, you're going to get a panic.  Can you verify that your FQDN resolves with e.g. `drill` or the like?

Also, in the future, can you please use a debug build that shows the line numbers in `stacks-node` where the panic occurred?

**Comment by CharlieC3** [comment]
@jcnelson I just noticed a typo in the FQDN. When I tested this yesterday (with curl), I must've tested it with the correct FQDN in the running `stacks-blockchain` pod whereas the stacks config file had the FQDN with the typo in it. So, this works as expected, I'm just blind :)

Closing this issue.
