### ISSUE TITLE
Mocknet panicked after submitting a transaction

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-blockchain#1623]
**Describe the bug**

Mocknet panicked:

```
INFO [1590170230.907] [src/chainstate/stacks/db/transactions.rs:511] Contract-call to ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.flip-coin.ClarityName("bet") args [UInt(10), Bool(true)] returned Response(ResponseData { committed: true, data: UInt(15) })
INFO [1590170230.907] [src/chainstate/stacks/db/transactions.rs:512] Contract-call to ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.flip-coin.ClarityName("bet") args [UInt(10), Bool(true)] cost ExecutionCost { write_length: 376, write_count: 7, read_length: 6292, read_count: 14, runtime: 9534 }
thread 'main' panicked at 'Tried to debit 247 from account ST1JDEC841ZDWN9CKXKJMDQGP5TW1AM10B7EV0DV9 (which only has 246)', src/chainstate/stacks/db/accounts.rs:167:17
```

**Steps To Reproduce**
This happened during trying [flip-coin contract](https://github.com/friedger/clarity-smart-contracts/blob/master/contracts/experiments/flip-coin.clar) and after I submitted transaction in https://github.com/friedger/clarity-smart-contracts/blob/master/test/integration/flip-coin2.ts

1. start mocknet with some stx for addresses in keys.json and keys2.json
1. clone repo and run `yarn` in the repo folder
1. deploy contract `yarn mocha test/integration/flip-coin0.ts`
1. call `bet` function: `yarn mocha test/integration/flip-coin1.ts`
1. adjust `betAtHeight` with the result from previous transaction and call `yarn mocha test/integration/flip-coin-x.ts` to check whether user won (should get winner returns some value - type 9)  (if none - type 10 - restart the process).
1. call `bet` to force payout`yarn mocha test/integration/flip-coin2.ts`
1. mocknet panics.

**Expected behavior**
mocknet should not crash

**Environment (please complete the following information):**
stacks-blockstack master commit 57f070775c1a5316e86d72e33e9148dd09e32b1f

starting node with 
```
[[mstx_balance]]
address = "ST1JDEC841ZDWN9CKXKJMDQGP5TW1AM10B7EV0DV9"
amount = 256

[[mstx_balance]]
address = "ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M"
amount = 67584
```

**Comment by friedger** [comment]
Here is a stack trace:

```
INFO [1590356839.388] [src/chainstate/stacks/db/transactions.rs:512] Contract-call to ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.flip-coin.ClarityName("bet") args [Bool(false)] cost ExecutionCost { write_length: 954, write_count: 6, read_length: 7777, read_count: 12, runtime: 9284 }
thread 'main' panicked at 'Tried to debit 230 from account ST1JDEC841ZDWN9CKXKJMDQGP5TW1AM10B7EV0DV9 (which only has 26)', src/chainstate/stacks/db/accounts.rs:167:17
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:472
  11: rust_begin_unwind
             at src/libstd/panicking.rs:380
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:334
  13: blockstack_lib::chainstate::stacks::db::accounts::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::account_debit::{{closure}}
             at src/chainstate/stacks/db/accounts.rs:167
  14: blockstack_lib::vm::clarity::ClarityTransactionConnection::with_clarity_db::{{closure}}
             at src/vm/clarity.rs:431
  15: blockstack_lib::vm::clarity::ClarityTransactionConnection::with_clarity_db
             at src/vm/clarity.rs:426
  16: blockstack_lib::chainstate::stacks::db::accounts::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::account_debit
             at src/chainstate/stacks/db/accounts.rs:161
  17: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::pay_transaction_fee
             at src/chainstate/stacks/db/transactions.rs:232
  18: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction
             at src/chainstate/stacks/db/transactions.rs:675
  19: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::try_mine_tx_with_len
             at src/chainstate/stacks/miner.rs:309
  20: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::build_anchored_block::{{closure}}
             at src/chainstate/stacks/miner.rs:638
  21: blockstack_lib::core::mempool::MemPoolDB::iterate_candidates
             at src/core/mempool.rs:392
  22: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::build_anchored_block
             at src/chainstate/stacks/miner.rs:621
  23: stacks_node::tenure::Tenure::run
             at testnet/stacks-node/src/tenure.rs:84
  24: stacks_node::run_loop::helium::RunLoop::start
             at testnet/stacks-node/src/run_loop/helium.rs:142
  25: stacks_node::main
             at testnet/stacks-node/src/main.rs:75
  26: std::rt::lang_start::{{closure}}
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  27: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  28: std::panicking::try::do_call
             at src/libstd/panicking.rs:305
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  30: std::panicking::try
             at src/libstd/panicking.rs:281
  31: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  32: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  33: std::rt::lang_start
             at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libstd/rt.rs:67
  34: main
  35: __libc_start_main
  36: _start
```

**Comment by jcnelson** [comment]
This should be fixed in `master` now.  Thanks @friedger!
