### ISSUE TITLE
miner panicked at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#1730]
## Describe the bug
Was running a miner for over 24h (nearly 48 hours I think), and the miner panicked with:
```
DEBUG [1594297336.457] [src/chainstate/stacks/index/storage.rs:1080] [ThreadId(24214)] Flush: identifier of self is 8637
DEBUG [1594297336.457] [src/chainstate/burn/db/burndb.rs:680] [ThreadId(24214)] Insert block snapshot state 76bbef12ef89fe118b2a077a2233f445f69b3a1273a2655d7c76c2dec4fb5b19 for block 8636 (3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229,6f74eb55c08bbaae46444e7465434a197b2002d380fffe9eb6a03ceef6ba7681) 8330
DEBUG [1594297336.457] [src/chainstate/burn/db/burndb.rs:965] [ThreadId(24214)] ACCEPTED(8636) leader key register 9c5bb2c072d5ad55ffb246cb9479c7b7c1f102481073e8a375254d5a8c61352c at 8636,1
DEBUG [1594297336.458] [src/chainstate/burn/db/burndb.rs:969] [ThreadId(24214)] ACCEPTED(8636) leader block commit 5a4ed1ba90ac3d4a35dc7441cd4955831c59e07e7f38ac4e7666628fa5392800 at 8636,2
DEBUG [1594297336.458] [src/chainstate/burn/db/burndb.rs:965] [ThreadId(24214)] ACCEPTED(8636) leader key register 41168f6cf646875714623e1b3580877289f74b24ffe039f89d88c9c325cd2151 at 8636,3
DEBUG [1594297336.459] [src/chainstate/burn/db/burndb.rs:969] [ThreadId(24214)] ACCEPTED(8636) leader block commit 630218037b8efb0bbb322e9c064451f1c4d24fd415d94e5e3c7eb85cae281a11 at 8636,4
DEBUG [1594297336.459] [src/burnchains/burnchain.rs:665] [ThreadId(24214)] OPS-HASH(8636): 1be9d3dd495fbc38ae59c486bdb07386f1132e882ae8ec33bb90b984bd2a9265
DEBUG [1594297336.459] [src/burnchains/burnchain.rs:666] [ThreadId(24214)] INDEX-ROOT(8636): 76bbef12ef89fe118b2a077a2233f445f69b3a1273a2655d7c76c2dec4fb5b19
DEBUG [1594297336.459] [src/burnchains/burnchain.rs:667] [ThreadId(24214)] SORTITION-HASH(8636): d3135a1038616d2ae5ec0dace3c818f01a53e01a9694294252313209b223d792
DEBUG [1594297336.459] [src/burnchains/burnchain.rs:668] [ThreadId(24214)] CONSENSUS(8636): e11771a85fef5eca2ff61964bd6bb647df2e7234

thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/burnchains/burnchain.rs:919:85

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/burnchains/burnchain.rs:946:60
```

And way earlier in the log (I was running with lots of additional logging), but the first prior `Try recv next parsed block` log:
```
DEBUG [1594297338.771] [src/burnchains/burnchain.rs:895] [ThreadId(24213)] Parsed block 8636 in 19ms

DEBUG [1594297338.771] [src/burnchains/burnchain.rs:908] [ThreadId(24214)] Try recv next parsed block

DEBUG [1594297338.771] [src/burnchains/burnchain.rs:760] [ThreadId(24214)] Process block 8636 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229
DEBUG [1594297338.771] [src/burnchains/burnchain.rs:706] [ThreadId(24214)] Get header for block 8636 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229
DEBUG [1594297338.771] [src/burnchains/burnchain.rs:499] [ThreadId(24214)] Extract Blockstack transactions from block 8636 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229
DEBUG [1594297338.772] [src/burnchains/burnchain.rs:680] [ThreadId(24214)] BEGIN(8636) block (3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229,6f74eb55c08bbaae46444e7465434a197b2002d380fffe9eb6a03ceef6ba7681)
DEBUG [1594297338.772] [src/burnchains/burnchain.rs:681] [ThreadId(24214)] Append 4 operation(s) from block 8636 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229
DEBUG [1594297338.772] [src/burnchains/burnchain.rs:608] [ThreadId(24214)] Check Blockstack transactions from block 8636 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229
```
which has a higher timestamp, so maybe the cause for the overflow?

and here's the part of the log where the "inversion" happened:
```
DEBUG [1594297338.938] [src/chainstate/stacks/index/trie.rs:745] [ThreadId(24214)] Next root hash is b6625fae007e2cb50026fa734d2f4ac129582599cdef73ec6ddaefb280b6b78b (update_skiplist=false)
DEBUG [1594297338.938] [src/chainstate/stacks/index/marf.rs:467] [ThreadId(24214)] MARF Insert in 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229: 'c3d18ea0eea5a15cfe8a1ca63912d728ce68d3b9389688138c38895ec2199f40' = '6f74eb55c08bbaae46444e7465434a197b2002d380fffe9eb6a03ceef6ba76810000000000000000' (...[])

DEBUG [1594297336.352] [src/chainstate/stacks/index/trie.rs:745] [ThreadId(24214)] Next root hash is b91e9d5d206cf411d4ea03d9840f76b7b943bd4a7b1a3b82845db22f050dfc4f (update_skiplist=false)
DEBUG [1594297336.353] [src/chainstate/stacks/index/marf.rs:467] [ThreadId(24214)] MARF Insert in 3d58d1edb7247e15cff6c2a496d07597bf2d9a2bb506ef5c794554834bbff229: 'c612882cf676e1d004ad9c4cc2ee70757b92fbcdc5ef4e732570058b4454ddb5' = 'bb210000000000000000000000000000000000000000000000000000000000000000000000000000' (...[])
DEBUG [1594297336.365] [src/chainstate/stacks/index/trie.rs:745] [ThreadId(24214)] Next root hash is acd85ff39cc9421273de68319227d3a017aa1c30046ff62d0af4083b6317806b (update_skiplist=true)
DEBUG [1594297336.365] [src/chainstate/stacks/index/marf.rs:786] [ThreadId(24214)] Opened 6f74eb55c08bbaae46444e7465434a197b2002d380fffe9eb6a03ceef6ba7681 in ./.stack/burnchain/db/bitcoin/regtest/burn.db/marf
```

Unfortunately, while trying to save the terminal, my mac rebooted (probably was over 100Gb), so I no longer have the whole log, but I can provide more logs right before the panic if needed.

The line numbers in `burnchain.rs` are consistent with current master.

## Steps To Reproduce

not sure how you would reproduce for sure... run for **a while**?

## Expected behavior

Don't panic would be preferable

## Environment

 - OS: Mac OS 10.14.6
 - Rust version: rustc 1.43.1 (8d69840ab 2020-05-04)

**Comment by jcnelson** [comment]
Bizarre.  What _might_ have happened (this is pure speculation, but is plausible) is that your OS synchronized its clock against a network time server, and discovered that the local clock was too far ahead and adjusted it backwards.  Depending on when this adjustment happened, this could have caused the `insert_after` timestamp to be less than the `insert_before` timestamp.

**Comment by psq** [comment]
that's a plausible theory.  As best I can tell, the mac uses `timed`, which rely on `ntp`/`sntp`, but it is not supposed to set the clock backwards, just slow it down so it eventually becomes correct.

about 2 seconds is a big gap.

**Comment by psq** [comment]
here's the log from `timed`, which runs quite often, so that would seems unlikely to see a 2 seconds drift unless something went really wrong

```
Jul 10 00:09:33 psq-mbp-2 timed[109]: settimeofday({0x5f08142d,0x91e17}) == 0
Jul 10 00:44:54 psq-mbp-2 timed[109]: settimeofday({0x5f081c76,0x684fb}) == 0
Jul 10 01:48:51 psq-mbp-2 timed[109]: settimeofday({0x5f082b73,0x71550}) == 0
Jul 10 02:23:36 psq-mbp-2 timed[109]: settimeofday({0x5f083398,0x84ff5}) == 0

bash-3.2# gzcat /var/log/system.log.0.gz |grep timed
Jul  9 01:10:43 psq-mbp-2 timed[109]: settimeofday({0x5f06d103,0x78add}) == 0
Jul  9 01:45:59 psq-mbp-2 timed[109]: settimeofday({0x5f06d947,0x495fb}) == 0
Jul  9 02:21:13 psq-mbp-2 timed[109]: settimeofday({0x5f06e189,0x734bb}) == 0
Jul  9 02:56:43 psq-mbp-2 timed[109]: settimeofday({0x5f06e9db,0x7b8c7}) == 0
Jul  9 03:30:28 psq-mbp-2 timed[109]: settimeofday({0x5f06f1c4,0x7d327}) == 0
Jul  9 04:39:35 psq-mbp-2 timed[109]: settimeofday({0x5f0701f7,0xa1ad8}) == 0
Jul  9 05:14:13 psq-mbp-2 timed[109]: settimeofday({0x5f070a15,0x7d52c}) == 0
Jul  9 05:22:16 psq-mbp-2 timed[109]: settimeofday({0x5f070bf8,0x54f57}) == 0
Jul  9 06:02:45 psq-mbp-2 timed[109]: settimeofday({0x5f071575,0x56c4}) == 0
Jul  9 08:56:59 psq-mbp-2 timed[109]: settimeofday({0x5f073e4b,0x1e2e4}) == 0
Jul  9 10:57:07 psq-mbp-2 timed[109]: settimeofday({0x5f075a72,0xf1a34}) == 0
Jul  9 12:05:13 psq-mbp-2 timed[109]: settimeofday({0x5f076a69,0xcae10}) == 0
Jul  9 14:56:43 psq-mbp-2 timed[109]: settimeofday({0x5f07929b,0x79768}) == 0
Jul  9 15:31:28 psq-mbp-2 timed[109]: settimeofday({0x5f079ac0,0x807e5}) == 0
Jul  9 16:05:13 psq-mbp-2 timed[109]: settimeofday({0x5f07a2a9,0xd3645}) == 0
Jul  9 17:55:55 psq-mbp-2 timed[109]: settimeofday({0x5f07bc9b,0xbdaa0}) == 0
Jul  9 18:00:05 psq-mbp-2 timed[109]: settimeofday({0x5f07bd95,0x4d32a}) == 0
Jul  9 22:26:36 psq-mbp-2 timed[109]: settimeofday({0x5f07fc0c,0x9aee4}) == 0

bash-3.2# gzcat /var/log/system.log.1.gz |grep timed
Jul  8 01:22:58 psq-mbp-2 timed[109]: settimeofday({0x5f058262,0x9b5d4}) == 0
Jul  8 02:32:45 psq-mbp-2 timed[109]: settimeofday({0x5f0592bd,0xe9bcf}) == 0
Jul  8 03:07:58 psq-mbp-2 timed[109]: settimeofday({0x5f059afe,0x72615}) == 0
Jul  8 04:16:58 psq-mbp-2 timed[109]: settimeofday({0x5f05ab2a,0x7a4a8}) == 0
Jul  8 04:51:43 psq-mbp-2 timed[109]: settimeofday({0x5f05b34f,0x86a29}) == 0
Jul  8 07:09:43 psq-mbp-2 timed[109]: settimeofday({0x5f05d3a7,0x75a21}) == 0
Jul  8 07:44:58 psq-mbp-2 timed[109]: settimeofday({0x5f05dbea,0x75acb}) == 0
Jul  8 08:20:28 psq-mbp-2 timed[109]: settimeofday({0x5f05e43c,0x7f8fd}) == 0
Jul  8 09:30:09 psq-mbp-2 timed[109]: settimeofday({0x5f05f491,0x58da7}) == 0
Jul  8 10:37:33 psq-mbp-2 timed[109]: settimeofday({0x5f06045d,0x6c70d}) == 0
Jul  8 11:11:28 psq-mbp-2 timed[109]: settimeofday({0x5f060c50,0x77222}) == 0
Jul  8 12:19:28 psq-mbp-2 timed[109]: settimeofday({0x5f061c40,0x8fe37}) == 0
Jul  8 12:54:13 psq-mbp-2 timed[109]: settimeofday({0x5f062465,0xacc85}) == 0
Jul  8 15:45:03 psq-mbp-2 timed[109]: settimeofday({0x5f064c6f,0x699f3}) == 0
Jul  8 16:19:58 psq-mbp-2 timed[109]: settimeofday({0x5f06549e,0x7eaed}) == 0
Jul  8 23:03:13 psq-mbp-2 timed[109]: settimeofday({0x5f06b321,0x2be76}) == 0
```

**Comment by diwakergupta** [comment]
Two concrete follow-ups:

1. Use process time instead of wall clock time
2. Use checked subtract instead of raw subtraction so we don't panic and can better handle these kinds of errors

@psq to confirm, the clock skew is measured in milliseconds, so there was 2ms gap not a 2s gap, which might be more likely due to a clock skew than a 2 second gap.

**Comment by psq** [comment]
ah, ok.  2ms seems more likely.  Good follow ups btw.

**Comment by jcnelson** [comment]
Combing through the codebase, I think that's the only place we subtract two millisecond timestamps.  Will replace with `saturating_sub` in my outstanding PR.

**Comment by psq** [comment]
closing as the fix from @jcnelson should address this issue.
