### ISSUE TITLE
Consistently getting ConflictingNonceInMempool via faucet

### ISSUE THREAD

**Issue by aulneau** [blockstack/stacks-blockchain#2144]
```json
error: "Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {"error":"transaction rejected","reason":"ConflictingNonceInMempool","txid":"50b3df6632bfb7d9a4481d47741f4a68aed3da63143c54de22b738b499080938"}"
errorTag: "4bb4ca18-d85f-40d6-a38d-047eade37433"
stack: "Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {"error":"transaction rejected","reason":"ConflictingNonceInMempool","txid":"50b3df6632bfb7d9a4481d47741f4a68aed3da63143c54de22b738b499080938"}↵    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)↵    at runMicrotasks (<anonymous>)↵    at processTicksAndRejections (internal/process/task_queues.js:93:5)↵    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)↵    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)↵    at async /app/lib/api/routes/faucets.js:140:42↵    at async run (/app/node_modules/p-queue/dist/index.js:159:29)"
```

I've not been able to successfully request funds from the faucet over the last couple of days, and when I was able to get a TX through, it was rejected due to an incorrect nonce. -> https://testnet-explorer.blockstack.org/txid/0x9aab6665de61e8207dd21ec7d21e751c340f5c7618b1175c8c141ee26783797c

```
Reject transaction 9aab6665de61e8207dd21ec7d21e751c340f5c7618b1175c8c141ee26783797c: BadNonces(TransactionNonceMismatch { expected: 112, actual: 1, txid: 9aab6665de61e8207dd21ec7d21e751c340f5c7618b1175c8c141ee26783797c, principal: Standard(StandardPrincipalData(26, [22, 66, 71, 214, 242, 180, 37, 172, 87, 113, 66, 58, 230, 200, 12, 117, 79, 113, 114, 176])), is_origin: true, quiet: true })
```

From Diwaker via discord: 
> the difference between actual and expected nonce value in this case is also surprising, like it's not off by a bit, it's off by a lot

**Comment by jcnelson** [comment]
We believe we've merged a fix for this.  Can you let us know if you're still seeing the issue?

**Comment by diwakergupta** [comment]
Yep, still seeing the issue:

```
$ curl -X POST "https://stacks-node-api.xenon.blockstack.org/extended/v1/faucets/stx?address=ST2F02DZ6KFSFYRP4BB0B6N8YW33VVBEN4FP0WVDP"
{"error":"Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041\"}","stack":"Error: Response 400: Bad Request fetching http://stacks-node-follower.prod-xenon.svc.cluster.local:20443/v2/transactions - {\"error\":\"transaction rejected\",\"reason\":\"ConflictingNonceInMempool\",\"txid\":\"c317af3fa1e6929ac5086493fa7c2590466e67e6a61bb5180c84ec84b2104041\"}\n    at StacksCoreRpcClient.fetchText (/app/lib/core-rpc/client.js:72:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async StacksCoreRpcClient.fetchJson (/app/lib/core-rpc/client.js:51:30)\n    at async StacksCoreRpcClient.sendTransaction (/app/lib/core-rpc/client.js:107:24)\n    at async /app/lib/api/routes/faucets.js:140:42\n    at async run (/app/node_modules/p-queue/dist/index.js:159:29)","errorTag":"23f3aa16-563d-4334-b73c-27900d24a5c3"}
```

**Comment by diwakergupta** [comment]
I think we can close this in favor of #2193 , unless we suspect there's any other issue here at play.

**Comment by jcnelson** [comment]
Pretty sure this is fixed; please re-open if you see it again.
