### ISSUE TITLE
UNIQUE constraint failed in clarity-cli REPL

### ISSUE THREAD

**Issue by psq** [blockstack/stacks-blockchain#2215]
First issue (found afterwards, but looks the same).

Start REPL with
```
RUST_BACKTRACE=1 node_modules/@blockstack/clarity-native-bin/.native-bin/v24.2.1.0-xenon/clarity-cli repl
```
press Enter once, and you get
```
Execution error:
ParseError("Expected a program of at least length 1")
```
press Enter a second time, and you get
```
ERRO [1608771045.493938] [src/vm/database/sqlite.rs:102] [ThreadId(1)] Failed to insert (ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,clr-meta::S1G2081040G2081040G2081040G208105NK8PE5.__transient::analysis,{"contract_identifier":{"issuer":[1,[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],"name":"__transient"},"private_function_types":{},"variable_types":{},"public_function_types":{},"read_only_function_types":{},"map_types":{},"persisted_variable_types":{},"fungible_tokens":[],"non_fungible_tokens":{},"defined_traits":{},"implemented_traits":[],"contract_interface":{"functions":[],"variables":[],"maps":[],"fungible_tokens":[],"non_fungible_tokens":[]},"is_cost_contract_eligible":true}): SqliteFailure(Error { code: ConstraintViolation, extended_code: 2067 }, Some("UNIQUE constraint failed: metadata_table.key, metadata_table.blockhash"))
thread 'main' panicked at 'PANIC: SQL Failure in Smart Contract VM.', src/vm/database/sqlite.rs:109:17
stack backtrace:
   0: std::panicking::begin_panic
   1: blockstack_lib::vm::database::sqlite::SqliteConnection::insert_metadata
   2: blockstack_lib::vm::database::marf::ClarityBackingStore::put_all_metadata
   3: blockstack_lib::vm::database::key_value_wrapper::RollbackWrapper::commit
   4: blockstack_lib::vm::analysis::analysis_db::AnalysisDatabase::execute
   5: blockstack_lib::vm::analysis::run_analysis
   6: blockstack_lib::clarity::run_analysis
   7: blockstack_lib::clarity::invoke_command
   8: clarity_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Same thing happens when using correct clarity code, the second eval gives you a panic

Example:
```
>  (merge  (merge {a: 1, b: 1} {b: 2}) {a: 4})
(tuple (a 4) (b 2))
>  (merge  (merge {a: 1, b: 1} {b: 2}) {a: 4})
ERRO [1608771160.795630] [src/vm/database/sqlite.rs:102] [ThreadId(1)] Failed to insert (ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff,clr-meta::S1G2081040G2081040G2081040G208105NK8PE5.__transient::analysis,{"contract_identifier":{"issuer":[1,[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]],"name":"__transient"},"private_function_types":{},"variable_types":{},"public_function_types":{},"read_only_function_types":{},"map_types":{},"persisted_variable_types":{},"fungible_tokens":[],"non_fungible_tokens":{},"defined_traits":{},"implemented_traits":[],"contract_interface":{"functions":[],"variables":[],"maps":[],"fungible_tokens":[],"non_fungible_tokens":[]},"is_cost_contract_eligible":true}): SqliteFailure(Error { code: ConstraintViolation, extended_code: 2067 }, Some("UNIQUE constraint failed: metadata_table.key, metadata_table.blockhash"))
thread 'main' panicked at 'PANIC: SQL Failure in Smart Contract VM.', src/vm/database/sqlite.rs:109:17
stack backtrace:
   0: std::panicking::begin_panic
   1: blockstack_lib::vm::database::sqlite::SqliteConnection::insert_metadata
   2: blockstack_lib::vm::database::marf::ClarityBackingStore::put_all_metadata
   3: blockstack_lib::vm::database::key_value_wrapper::RollbackWrapper::commit
   4: blockstack_lib::vm::analysis::analysis_db::AnalysisDatabase::execute
   5: blockstack_lib::vm::analysis::run_analysis
   6: blockstack_lib::clarity::run_analysis
   7: blockstack_lib::clarity::invoke_command
   8: clarity_cli::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

That panic should not happen.

This is using `@blockstack/clarity-cli` version 0.3.5 with this command:
```
node_modules/@blockstack/clarity-native-bin/.native-bin/v24.2.1.0-xenon/clarity-cli repl
```

same behavior while building locally, with line numbers:
```
   0: std::panicking::begin_panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
   1: blockstack_lib::vm::database::sqlite::SqliteConnection::insert_metadata
             at ./src/vm/database/sqlite.rs:109
   2: blockstack_lib::vm::database::marf::ClarityBackingStore::insert_metadata
             at ./src/vm/database/marf.rs:127
   3: blockstack_lib::vm::database::marf::ClarityBackingStore::put_all_metadata
             at ./src/vm/database/marf.rs:147
   4: blockstack_lib::vm::database::key_value_wrapper::RollbackWrapper::commit
             at ./src/vm/database/key_value_wrapper.rs:257
   5: blockstack_lib::vm::analysis::analysis_db::AnalysisDatabase::commit
             at ./src/vm/analysis/analysis_db.rs:72
   6: blockstack_lib::vm::analysis::analysis_db::AnalysisDatabase::execute
             at ./src/vm/analysis/analysis_db.rs:63
   7: blockstack_lib::vm::analysis::run_analysis
             at ./src/vm/analysis/mod.rs:94
   8: blockstack_lib::clarity::run_analysis
             at ./src/clarity.rs:136
   9: blockstack_lib::clarity::invoke_command
             at ./src/clarity.rs:655
  10: clarity_cli::main
             at ./src/clarity_cli.rs:31
  11: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
```

**Comment by jcnelson** [comment]
It's unclear that we use this code in any of the automated testing.  It might be an orphaned artifact, in which case, it should be removed.
